version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mango-ripeness-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PORT=8000
    restart: unless-stopped
    networks:
      - mango-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mango-ripeness-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mango-network

networks:
  mango-network:
    driver: bridge
